name: CI

on:
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Unit testing
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup testing environment
      run: make setup_test_env

    - name: Run tests
      run: make run_tests

  
  build_publish:
    name: Build & Publish
    runs-on: ubuntu-18.04
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Inject variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{secrets.GHCR_USERNAME}}/${{env.GITHUB_REPOSITORY_NAME_PART_SLUG}}:latest
          ghcr.io/${{secrets.GHCR_USERNAME}}/${{env.GITHUB_REPOSITORY_NAME_PART_SLUG}}:${{env.GITHUB_SHA_SHORT}}

  deploy:
    name: Deploy  
    runs-on: ubuntu-18.04
    needs: build_publish
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
          SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}  

      - name: Deploy to the server
        run: ssh prod '~/scripts/deploy.sh'