name: CI

on:
  push:
    branches: [ master ]
  
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Unit testing
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup testing environment
      run: make setup_test_env

    - name: Run tests
      run: make run_tests
